/**
 * Type stub for big-src.ts, which is generated by run.ts and gitignored.
 * Keeps `tsc --noEmit` green in fresh checkouts where the fixture hasn't
 * been generated yet. When big-src.ts exists on disk, TypeScript resolves
 * the import to the real implementation and ignores this file.
 */
export const fns: ((x: number) => number)[];
