/**
 * Same error workload as harness.ts, but bundled with big-src.ts (generated by
 * run.ts) so the embedded sourcemap is realistically large. Measures whether
 * oven-sh/bun#39800's per-resolution leak scales with map size.
 *
 * Env: HARNESS_ITERS / HARNESS_DEPTH / HARNESS_SAMPLE — see harness.ts
 */
import { fns } from "./big-src";

const TOTAL = Number(process.env.HARNESS_ITERS ?? 150_000);
const DEPTH = Number(process.env.HARNESS_DEPTH ?? 48);
const SAMPLE = Number(process.env.HARNESS_SAMPLE ?? 5_000);

// Touch every function so nothing is tree-shaken out of the bundle/map.
let warm = 0;
for (const fn of fns) warm += fn(1);
if (warm === -1) console.log("unreachable");

function recurse(n: number): never {
  if (n <= 0) throw new Error(`boom-${Math.random()}`);
  return recurse(n - 1);
}

function resolveStack(err: Error): number {
  const s = err.stack ?? "";
  return s.length + s.split("\n").length;
}

async function main() {
  const rssKb = () => Math.round(process.memoryUsage().rss / 1024);
  console.log(`config iters=${TOTAL} depth=${DEPTH} sampleEvery=${SAMPLE}`);
  console.log(`t=0s\trss=${rssKb()}KB`);

  let checksum = 0;
  const t0 = Date.now();
  for (let i = 1; i <= TOTAL; i++) {
    try {
      recurse(DEPTH);
    } catch (err) {
      checksum += resolveStack(err as Error);
    }
    if (i % SAMPLE === 0) {
      const secs = ((Date.now() - t0) / 1000).toFixed(1);
      console.log(`t=${secs}s\ti=${i}\trss=${rssKb()}KB`);
    }
  }

  Bun.gc(true);
  await new Promise((r) => setTimeout(r, 1000));
  Bun.gc(true);
  console.log(
    `done in ${((Date.now() - t0) / 1000).toFixed(1)}s finalRssAfterGc=${rssKb()}KB checksum=${checksum % 97}`,
  );
}

main();
