#!/usr/bin/env bun
/**
 * Builds every sourcemap variant of the harness (small + large bundle), runs
 * each under an identical error workload, reports RSS growth slopes, then
 * deletes the binaries unless --keep is passed.
 *
 * Usage:  bun run test/sourcemap-rss/run.ts [--keep]
 */

import fs from "fs";
import path from "path";

const here = import.meta.dirname!;
const outDir = path.join(here, ".out");
const keepBinaries = process.argv.includes("--keep");

// Must match the harness default — the harness reads this same env var.
const RUN_ITERS = Number(process.env.HARNESS_ITERS ?? 150_000);

// ─── Generate the large-bundle fixture (realistically sized map) ────────────

const BIG_FNS = 20_000;

function generateBigSource(): string {
  const lines: string[] = [
    "// generated by run.ts — do not edit",
    "const fns: ((x: number) => number)[] = [];",
  ];
  for (let i = 0; i < BIG_FNS; i++) {
    lines.push(`export function fn${i}(x: number): number { const y = x * ${i % 7}; return y + ${i}; }`);
    lines.push(`fns.push(fn${i});`);
  }
  lines.push("export { fns };");
  return lines.join("\n") + "\n";
}

// harness-big.ts imports "./big-src" — regenerate next to it before building.
fs.writeFileSync(path.join(here, "big-src.ts"), generateBigSource());

// ─── Build variants ────────────────────────────────────────────────────────

interface Variant {
  name: string;
  entrypoint: string;
  sourcemap: "none" | "linked";
}

const variants: Variant[] = [
  { name: "small-none", entrypoint: "./harness.ts", sourcemap: "none" },
  { name: "small-linked", entrypoint: "./harness.ts", sourcemap: "linked" },
  { name: "big-none", entrypoint: "./harness-big.ts", sourcemap: "none" },
  { name: "big-linked", entrypoint: "./harness-big.ts", sourcemap: "linked" },
];

fs.mkdirSync(outDir, { recursive: true });

for (const variant of variants) {
  const t0 = Date.now();
  const result = await Bun.build({
    entrypoints: [path.join(here, variant.entrypoint)],
    compile: { outfile: path.join(outDir, variant.name) },
    format: "esm",
    minify: true,
    ...(variant.sourcemap === "none" ? {} : { sourcemap: variant.sourcemap }),
  });
  if (!result.success) {
    for (const log of result.logs) console.error(log);
    process.exit(1);
  }
  const sizeMb = fs.statSync(path.join(outDir, variant.name)).size / 1024 / 1024;
  console.log(`built ${variant.name}: ${sizeMb.toFixed(1)}MB in ${Date.now() - t0}ms`);
}

// ─── Run each variant and compute late-phase RSS slope ─────────────────────

interface Sample {
  iter: number;
  rssKb: number;
}

function parseSamples(stdout: string): Sample[] {
  return stdout
    .split("\n")
    .map((line) => line.match(/i=(\d+)\trss=(\d+)KB/))
    .filter((m): m is RegExpMatchArray => m !== null)
    .map((m) => ({ iter: Number(m[1]), rssKb: Number(m[2]) }));
}

/** Bytes of RSS growth per error resolution, measured over the second half of
 * the run so compiler/JIT warmup (which plateaus for every variant) is excluded. */
function bytesPerResolution(samples: Sample[], totalIters: number): number | null {
  const late = samples.filter((s) => s.iter >= totalIters / 2);
  if (late.length < 2) return null;
  const first = late[0]!;
  const last = late[late.length - 1]!;
  return ((last.rssKb - first.rssKb) * 1024) / (last.iter - first.iter);
}

console.log("\n=== running workloads ===");
const slopes = new Map<string, number>();
for (const variant of variants) {
  console.log(`\n--- ${variant.name} ---`);
  const proc = Bun.spawnSync([path.join(outDir, variant.name)], {
    env: { ...process.env },
    stdout: "pipe",
    stderr: "inherit",
  });
  const stdout = new TextDecoder().decode(proc.stdout);
  console.log(stdout.trimEnd());
  const slope = bytesPerResolution(parseSamples(stdout), RUN_ITERS);
  if (slope !== null) slopes.set(variant.name, slope);
}

// ─── Summary ───────────────────────────────────────────────────────────────

console.log("\n=== summary (late-phase RSS growth per stack resolution) ===");
for (const [name, bytes] of slopes) {
  console.log(`${name.padEnd(14)} ${bytes.toFixed(1)} B/resolution ${bytes > 100 ? "← LEAKING" : "(plateau)"}`);
}
console.log(
  "\nExpected: none-variants plateau (~0 B); linked-variants grow linearly.",
  "\nReference 2026-08-22, Bun 1.3.14: ~212 B (small map) / ~305 B (big map).",
  "\nIssue: https://github.com/oven-sh/bun/issues/39800",
);

if (!keepBinaries) {
  fs.rmSync(outDir, { recursive: true, force: true });
  console.log("\ncleaned .out/");
}
