/**
 * AUTO-GENERATED by bin/sync-ide-extension.ts — do not hand-edit.
 * Source of truth is packages/vscode-extension/src/extension.ts. Regenerate
 * with `bun run sync:ide-extension` (also runs automatically as part of the
 * CLI build/compile scripts).
 *
 * Embedded as string constants (not read from packages/vscode-extension/out/
 * at runtime) so extraction works identically across compiled binaries, npm
 * installs, and curl/iex installs, with no filesystem dependency on a
 * sibling package.
 */

export const EXTENSION_VERSION = "0.7.0";

export const EXTENSION_PACKAGE_JSON = JSON.stringify(
  {
    name: "koincode-vscode",
    displayName: "KOINCODE",
    description: "IDE context bridge for KOINCODE — surfaces the active file and text selection in the terminal agent status bar.",
    version: EXTENSION_VERSION,
    engines: {"vscode":"^1.80.0"},
    categories: ["Other"],
    activationEvents: ["onStartupFinished"],
    main: "./out/extension.js",
    contributes: {},
  },
  null,
  2,
);

export const EXTENSION_JS = `"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.activate = activate;
exports.deactivate = deactivate;
const vscode = __importStar(require("vscode"));
const fs = __importStar(require("node:fs"));
const path = __importStar(require("node:path"));
const os = __importStar(require("node:os"));
// Deliberately not imported from @koincode/shared: that package's package.json
// exports raw .ts source with no compiled output, resolvable only under Bun's
// runtime/resolver — never under the plain Node.js the VS Code extension host
// actually runs on. Keep these in sync with packages/shared/src/paths.ts by hand.
const GLOBAL_CONFIG_DIR = path.join(os.homedir(), ".koincode");
const IDE_CONTEXT_FILE = path.join(GLOBAL_CONFIG_DIR, "ide-context.json");
const NOTIFY_REQUEST_FILE = path.join(GLOBAL_CONFIG_DIR, "notify-request.json");
// Selected text is capped so a huge selection can't balloon the context file
// (and, downstream, the chat request body) — truncated with a marker instead
// of dropped entirely.
const MAX_SELECTION_CHARS = 20_000;
// Both fields live in one file, so they're tracked in memory and written
// together — writing just one would clobber whichever field changed most
// recently on the other axis.
let currentActiveFile = null;
let currentSelection = null;
function writeIdeContext() {
    try {
        fs.mkdirSync(GLOBAL_CONFIG_DIR, { recursive: true });
        fs.writeFileSync(IDE_CONTEXT_FILE, JSON.stringify({ activeFile: currentActiveFile, selection: currentSelection }));
    }
    catch {
        // Non-fatal — the status bar just won't update.
    }
}
function setActiveFile(filePath) {
    currentActiveFile = filePath;
    writeIdeContext();
}
function setSelection(editor) {
    if (!editor || editor.selection.isEmpty) {
        currentSelection = null;
    }
    else {
        let text = editor.document.getText(editor.selection);
        if (text.length > MAX_SELECTION_CHARS) {
            text = \`\${text.slice(0, MAX_SELECTION_CHARS)}...truncated\`;
        }
        currentSelection = {
            file: editor.document.fileName,
            startLine: editor.selection.start.line + 1,
            endLine: editor.selection.end.line + 1,
            text,
        };
    }
    writeIdeContext();
}
// Fallback for terminals that ignore BEL (VS Code's integrated terminal does,
// unless the user opts into a bell setting). The CLI writes a notify request
// here when it wants the user's attention; we relay it as an in-editor toast.
// \`lastNotifiedAt\` starts at activation time so a stale leftover file from a
// previous session never fires immediately on startup.
let lastNotifiedAt = Date.now();
function checkNotifyRequest() {
    try {
        const raw = fs.readFileSync(NOTIFY_REQUEST_FILE, "utf8");
        const data = JSON.parse(raw);
        if (typeof data.message === "string" &&
            typeof data.at === "number" &&
            data.at > lastNotifiedAt) {
            lastNotifiedAt = data.at;
            void vscode.window.showInformationMessage(data.message);
        }
    }
    catch {
        // No request file yet, or it was malformed — nothing to show.
    }
}
function activate(context) {
    // Write whatever is open (and selected) right now on activation.
    setActiveFile(vscode.window.activeTextEditor?.document.fileName ?? null);
    setSelection(vscode.window.activeTextEditor);
    const activeEditorDisposable = vscode.window.onDidChangeActiveTextEditor((editor) => {
        setActiveFile(editor?.document.fileName ?? null);
        setSelection(editor);
    });
    context.subscriptions.push(activeEditorDisposable);
    const selectionDisposable = vscode.window.onDidChangeTextEditorSelection((e) => {
        if (e.textEditor !== vscode.window.activeTextEditor)
            return; // ignore inactive panes
        setSelection(e.textEditor);
    });
    context.subscriptions.push(selectionDisposable);
    try {
        fs.mkdirSync(GLOBAL_CONFIG_DIR, { recursive: true });
        const watcher = fs.watch(GLOBAL_CONFIG_DIR, (_event, filename) => {
            if (filename !== "notify-request.json")
                return;
            checkNotifyRequest();
        });
        context.subscriptions.push({ dispose: () => watcher.close() });
    }
    catch {
        // Non-fatal — notifications just won't relay through the editor.
    }
}
function deactivate() {
    currentActiveFile = null;
    currentSelection = null;
    writeIdeContext();
}
`;
